export const navigationStrings = {
  AUTHSTACK: 'AuthStack',
  BOTTOMTABSNAV: 'BottomTabsNav',
  DASHBOARD: 'Dashboard',
  ACTIVITY: 'Activity',
  MOVEMONEY: 'Move Money',
  ACCOUNT: 'Account',
  APPS: 'Apps',
  INTRO: 'Intro',
  LOGIN: 'Login',
  RESETPASSWORD: 'Reset Password',
  TRANSACTIONS: 'Transactions',
  FINANCIALINSIGHTS: 'Financial Insights',
  MAKEPAYMENT: 'Make Payment',
  ADDPAYEE: 'Add Payee',
  BANKTRANSFER: 'Bank Transfer',
  PAPERCHECK: 'Paper Check',
  FUNDACCOUNT: 'Fund Account',
  CONNECTEDPAYPLATFORMS: 'Connected Payment Platforms',
  TRANSFERVIRTUALCARD: 'Transfer Virtual Card',
  PUSHFUND: 'Push Fund',
  DEPOSITCHECK: 'Deposit Check',
  VERIFYIDENTITY: 'Verify Identity',
  SELECTIDADD: 'Select Id Add',
  USDRIVERLICENSE: 'Us Driver License',
  SCANID: 'Scan Id',
  MAKEDEPOSIT: 'Make Deposit',
  DEPOSITCHECKAMT: 'Deposit Check Amount',
  SIGNENDORSE: 'SignEndorse',
  CAPTURECHECKNOTE: 'Capture Check Note',
  DEPOSITCHECKNAME: 'Deposit Check Name',
  SETTINGS: 'Settings',
  PERSONALINFORMATION: 'Personal Information',
  EDITEMAIL: 'Edit Email',
  EDITMOBILEPHONE: 'Edit Mobile Phone',
  EDITHOMEADDRESS: 'Edit Home Address',
  BUSINESSINFORMATION: 'Business Information',
  DBA: 'DBA',
  EDITBUSINESSPHONE: 'Edit Business Phone',
  EDITBUSINESSADDRESS: 'Edit Business Address',
  EDITMAILINGADDRESS: 'Edit Mailing Address',
  USERS: 'Users',
  ADDUSERREQ: 'Add User Request',
  BANKLETTER: 'Bank Letter',
  TRANSFERLIMITS: 'Transfer Limits',
  CHANGEPASSWORD: 'Change Password',
  REQLIMITCHANGE: 'Request Limit Change',
  RETHINKCARD: 'Rethink Card',
  RETHINKPHYSICAL: 'Rethink Physical',
  ACTIVATECARD: 'Activate Card',
  CHANGEPIN: 'Change Pin',
  TRAVELNOTICE: 'Travel Notice',
  MAKETRAVELNOTICE: 'Make Travel Notice',
  REPORTMISSINGCARD: 'Report Missing Card',
  STATEMENTS: 'Statements',
  REFERRALS: 'Referrals',
  VIRTAULCARD: 'Virtaul Card',
  VIRTAULCARDDETAIL: 'Virtaul Card Detail',
  CONFIRMPASSWORD: 'Confirm Password',
};
