export const navigationStrings = {
  AUTHSTACK: 'AuthStack',
  BOTTOMTABSNAV: 'BottomTabsNav',
  DASHBOARD: 'Dashboard',
  ACTIVITY: 'Activity',
  MOVEMONEY: 'Move Money',
  ACCOUNT: 'Account',
  APPS: 'Apps',
  INTRO: 'Intro',
  LOGIN: 'Login',
  RESETPASSWORD: 'Reset Password',
  TRANSACTIONS: 'Transactions',
  FINANCIALINSIGHTS: 'Financial Insights',
  MAKEPAYMENT: 'Make Payment',
  ADDPAYEE: 'Add Payee',
  BANKTRANSFER: 'Bank Transfer',
  PAPERCHECK: 'Paper Check',
  FUNDACCOUNT: 'Fund Account',
  CONNECTEDPAYPLATFORMS: 'Connected Payment Platforms',
  TRANSFERVIRTUALCARD: 'Transfer Virtual Card',
  PUSHFUND: 'Push Fund',
  DEPOSITCHECK: 'Deposit Check',
  VERIFYIDENTITY: 'Verify Identity',
  SELECTIDADD: 'Select Id Add',
  USDRIVERLICENSE: 'Us Driver License',
  SCANID: 'Scan Id',
};
