export const Strings = {
  introTitle: 'Ready for great business banking?',
  introSubtitle:
    'Novo is modern banking for businesses,\nfreelancres, and entrepreneurs in the U.S.',
  applyNow: 'Apply Now',
  completeApplication: 'Complete Existing Application',
  alreadyAccount: 'I have an Account',
  introNote:
    'Novo is financial technology company, not a bank.\nBanking service are provided by Middlesex Federal Savings, F.A; Member FDIC.',
  login: 'Log In',
  email: 'EMAIL',
  password: 'PASSWORD',
  resetPassword: 'Reset password?',
  newToRethink: 'New to Rethink?',
  emailQuestion: "What's the email you used to sign up?",
  confirm: 'Confirm',
  joinRethink: 'JOIN\nRETHINK',
  fundAccount: 'FUND\nACCOUNT',
  gameTime: 'GAME\nTIME',
  activateRethink: 'Activate Rethink',
  balances: 'Balances',
  availableBalance: 'Available Balance',
  reserves: 'Reserves',
  reservesHoldings: 'Reserves Holdings',
  pending: 'Panding',
  overallBalance: 'Overall Balance',
  moneyIn: 'Money In',
  moneyOut: 'Money Out',
  exploreRethink: "Explore Rethink's\nintrgrated apps all in\none place",
  seeMore: 'See More',
  fundAccount: 'Fund Account',
  addMoneyRethink: 'Add Money to Rethink',
  wayFund: 'Ways to fund',
  invoices: 'Invoices',
  sendTrackInvoice: 'Send & track invoices from\nyour Rethink account',
  createInvoice: 'Create an Invoice',
  reserves: 'Reserves',
  setAsideMoney: 'Set aside money for\nanythig',
  createReserve: 'Create a Reserve',
  referBusiness: 'Refer a Business',
  referNote:
    'Get $40 for you and your\nrefferal when they open\nand fund an account.',
  getStarted: 'Get Started',
  rethinkBoost: 'Rethink Boost',
  connectToStripe:
    'Connect to our Stripe\nintegration to get\npaid two days early.',
  seeMore: 'See More',
  noTransaction: 'No transaction yet',
  quote:
    "Time goes on. So whatever you're going\nto do, do it. Do it now. Don't wait.",
  quoteAuthor: '-Robert De Niro',
};
