export const Strings = {
  introTitle: 'Ready for great business banking?',
  introSubtitle:
    'Novo is modern banking for businesses,\nfreelancres, and entrepreneurs in the U.S.',
  applyNow: 'Apply Now',
  completeApplication: 'Complete Existing Application',
  alreadyAccount: 'I have an Account',
  introNote:
    'Novo is financial technology company, not a bank.\nBanking service are provided by Middlesex Federal Savings, F.A; Member FDIC.',
  login: 'Log In',
  email: 'EMAIL',
  password: 'PASSWORD',
  resetPassword: 'Reset password?',
  newToRethink: 'New to Rethink?',
  emailQuestion: "What's the email you used to sign up?",
  confirm: 'Confirm',
  joinRethink: 'JOIN\nRETHINK',
  fundAccount: 'FUND\nACCOUNT',
  gameTime: 'GAME\nTIME',
  activateRethink: 'Activate Rethink',
  balances: 'Balances',
  availableBalance: 'Available Balance',
  reserves: 'Reserves',
  reservesHoldings: 'Reserves Holdings',
  pending: 'Panding',
  overallBalance: 'Overall Balance',
  moneyIn: 'Money In',
  moneyOut: 'Money Out',
  exploreRethink: "Explore Rethink's\nintrgrated apps all in\none place",
  seeMore: 'See More',
  fundAccount: 'Fund Account',
  addMoneyRethink: 'Add Money to Rethink',
  wayFund: 'Ways to fund',
  invoices: 'Invoices',
  sendTrackInvoice: 'Send & track invoices from\nyour Rethink account',
  createInvoice: 'Create an Invoice',
  reserves: 'Reserves',
  setAsideMoney: 'Set aside money for\nanythig',
  createReserve: 'Create a Reserve',
  referBusiness: 'Refer a Business',
  referNote:
    'Get $40 for you and your\nrefferal when they open\nand fund an account.',
  getStarted: 'Get Started',
  rethinkBoost: 'Rethink Boost',
  connectToStripe:
    'Connect to our Stripe\nintegration to get\npaid two days early.',
  seeMore: 'See More',
  noTransaction: 'No transaction yet',
  quote:
    "Time goes on. So whatever you're going\nto do, do it. Do it now. Don't wait.",
  quoteAuthor: '-Robert De Niro',
  filter: 'Filter',
  applyFilters: 'Apply Filters',
  transactionType: 'Transaction Type',
  selectAll: 'Select all',
  unSelectAll: 'Unselect all',
  dateRange: 'Date Range',
  from: 'From',
  to: 'To',
  transactionCategory: 'Transaction Category',
  category: 'Category',
  income: 'Income',
  spending: 'Spending',
  searchByName: 'Search by name',
  activity: 'Activity',
  accountCashFlow: 'Account Cash Flow',
  netCashFlow: 'Net Cash Flow',
  availableNow: 'Available Now',
  makePayment: 'Make a Payment',
  sendMoneyToPayees: 'Send money to your payees',
  fundConnectedBank: 'Fund from a connected bank',
  depositBusinessDayOneTwo: 'Deposit in 1-2 business days',
  connectPlatforms: 'Connect payment platforms',
  depositMinutes: 'Deposit in minutes',
  transferVirtualCard: 'Transfer with your virtual card',
  depositInstant: 'Deposit Instant',
  pushFundAnotherBank: 'Push fund from another bank',
  depositeCheckFromPhone: 'Deposit a check from your phone',
  depositBusinessDayOneFour: 'Deposit in 1-4 business days',
  free: 'Free',
  fast: 'Fast',
  HighlyRecommended: 'Highly Recommended',
  easy: 'Easy',
  recommended: 'Recommended',
  forLargeDeposits: 'For Large Deposits',
  forSmallDeposits: 'For Small Deposits',
  addPayee: 'Add Payee',
  addPayeesToSendPayments: 'Add your payees to send payments',
  sendMoneyPayeesBank:
    'Send money to your payees via bank transfer or paper check.',
  choosePayMethod: 'Choose a payment method',
  bankTransfer: 'Bank Transfer (ACH)',
  paperCheck: 'Paper Check',
  legalName: 'Legal Name',
  nickname: 'Nickname',
  accountNumber: 'Account Number',
  routingNumber: 'Routing Number',
  emailOptional: 'Email (Optional)',
  notes: 'Notes',
  checkingAccount: 'Checking Account',
  onlyVisible: 'Only visible to you',
  review: 'Review',
  type: 'Type',
  willAppearOnPaperCheck: 'This will appear on the paper check',
  address: 'Address',
  unitSuite: 'Unit / Suite',
  city: 'City',
  zip: 'Zip',
  state: 'State',
  seamlessDeposits: 'A seamless way to make smaller deposits',
  connectExternalBankAccount:
    'Connect an external bank account to make deposits. If you need to make large deposits. we recommend pushing funds from another bank.',
  addExternalAccount: 'Add External Account',
  bestOptionEarnMoney:
    'The best option if you earn money on major platforms and payment providers',
  usePlatforms:
    'Use platforms like Square, Stripe, and Shopfiy to directly deposit money into your Rethink account. Make sure that Rethink is your default bank account for any deposits you receive on these platforms.',
  goToRethinkApps: 'Go to Rethink Apps',
  goToApp: 'Go to app',
  venmo: 'Venmo',
  paypal: 'PayPal',
  addFundsCard: 'Add funds instantly with your card',
  copyPasteCard:
    'Copy and paste your virtual card details into one of the following:',
  greatOptionLargeDeposit: 'A great option to make a large deposit',
  initiateTransferExternalBank:
    'Initiate a transfer from an external bank account (no limits apply).',
  routingNumber: 'Routing Number',
  accountNumber: 'Account Number',
  view: 'View',
  easyWayLargeDeposits: 'An easy way to make large deposits to your account',
  depositCheckLimit:
    'Deposit check through the Rethink mobile app (up to $20,000 a day).',
  verifyIdentity: 'Verify Identity',
  addYourId: 'Add your ID and\ncomplete your profile',
  verifyIdentitySubtitle:
    "We must go the extra mile to protect your Rethink account from financial crime by making sure it's really you.",
  verifyYourIdentity: 'Verify Your Identity',
  takePhotoId: 'Take a photo of your ID',
  takephotoYourself: 'Take a photo of yourself',
  selectIdAdd: 'Select an ID to add',
  idMustBe: 'The ID must be:',
  unexpired: 'Unexpired',
  includesYourPhoto: 'Includes your photo',
  notTempId: 'Not a temporary ID',
  usDriverLicense: "U.S. Driver's License",
  passport: 'Passport',
  whenTakingPhoto: 'When Taking the PHOTOS:',
  goodLighting: 'Make sure you have good lighting',
  cornersVisible: 'All 4 corners are visible',
  frontLicense: 'Front of license',
  backLicense: 'Back of license',
  continue: 'Continue',
  scanId: 'Scan ID',
  cancelCapture: 'Cancel Capture',
  exitNote: 'Are you sure you want to exit?',
  positiveNote: "Yes, I'M Sure",
  nagativeNote: 'No, Go Back',
  alignDocument: 'Align document to frame',
  makeDeposit: 'Make Deposit',
  depositCheck: 'Deposit a check',
  amount: 'Amount',
  expectedAvailability: 'Expected Availability',
  depositCheckAmtNote:
    'Please note that currently, Rethink does not accept mobile deposits for MoneyGram money orders.',
  signEndorseNOne:
    'Sign the back of your check and write\n"For mobile deposit at Rethink"',
  signEndorseNTwo:
    'Keep in mind that once you endorse the check, it may only be deposited at Rethink.',
  signEndorseNThree:
    'I have signed the back of check and endorse it for mobile deposit at Rethink',
  signEndorseCheck: 'Sign and endorse check',
  checkNoteOne:
    'Center the check\non a dark surface,\nprovide ample\nlight. Align check.',
  checkNoteTwo: 'We will take the\nphoto for you.',
  cancelCapture: 'Cancel\nCapture',
  enterNamePayeeNote:
    'Please enter the name of the payee that is written on the check.',
  nameCheck: 'Name on the Check',
  checkAcceptNote:
    'For a check to be accepted, the name of the payee on the check must be registered to your account. Rethink only accepts checks for the below name in your account:',
  addUpdateDba: 'Add/Update DBA',
  settings: 'Settings',
  accountInformation: 'Account Information',
  personalInformation: 'Personal Information',
  businessInformation: 'Business Information',
  users: 'Users',
  bankLetter: 'Bank Letter',
  transferLimits: 'Transfer Limits',
  changePassword: 'Change Password',
  biometricAuthentication: 'Biometrics Authentication',
  appNotifications: 'App Notifications',
  linkedAccounts: 'Linked Accounts',
  logout: 'Log Out',
  version: 'Version',
  editEmail: 'Edit Email',
  emailQuestion: "What's your new email?",
  editEmailNote:
    "An email will be sent to your new email\naddress to verify it's you.",
  sendEmail: 'Send Email',
  editMobilePhone: 'Edit Mobile Phone',
  editPhoneQuestion: "What's your new mobile phone number?",
  mobilePhoneNumber: 'Mobile Phone Number',
  editMobilePhoneNote:
    'A SMS will be sent to your mobile phone number to\nverify its you. Message and data rates may apply',
  submit: 'Submit',
  editHomeAddress: 'Edit Home Address',
  homeAddress: 'Home Address',
  homeAddressQuestion: "What's your new home address?",
  mailingAddressQuestion: "What's your new mailing business address?",
  editMailingAddress: 'Edit Mailing Address',
  mailingAddress: 'Mailing Address',
  editBusinessAddress: 'Edit Business Address',
  businessAddress: 'Business Address',
  businessAddressQuestion: "What's your new physical business address?",
  editBusinessphone: 'Edit Business Phone',
  businessPhoneQuestion: "What's your new business phone?",
  businessPhone: 'Business Phone',
  editDba: 'Edit DBA',
  dbaQuestion: 'What\'s your new "Doing Business As"?',
  dba: 'DBA',
  addUserReq: 'Add User Request',
  userReqNote:
    "Enter the details of the person you'd like to add to your Rethink account and we'll send them an invite.",
  name: 'Name',
  useToCommunicate: 'This will be used for communication with user',
  relationBusiness: 'Relation to business',
  bankLetter: 'Bank Letter',
  bankLetterNote:
    'The Bank Letter is a document provided by our partner bank to demonstrate the banking relationship and ownership of the account.',
  bankTransferOnly: 'Bank Transfer',
  achPush: 'ACH Push from your Rethink account',
  perTransfer: 'Per Transfer',
  perDay: 'Per Day',
  perMonth: 'Per Month',
  transfersPerDay: 'Transfers Per Day',
  transfersPerMonth: 'Transfers Per Month',
  transactionPerDay: 'Transaction Per Day',
  requestLimitChange: 'Request a Limit Change',
  mailedCheck: 'Mailed Check',
  mailedCheckNote: 'Mail a check from your Rethink account',
  checkDeposit: 'Check Deposit',
  depositCheckTakePhoto: 'Deposit check by taking photo',
  atmWithdrawal: 'ATM Withdrawal',
  debitCard: 'Debit Card',
  posWithdrawal: 'POS Withdrawal(Purchasing from\nmerchant)',
  tranferFundTo: 'Transfer fund to Rethink',
  achPullExternal: 'ACH pull from external account',
  perCheck: 'Per Check',
  mustLetter: 'Must include letters',
  mustNumber: 'Must include numbers',
  mustSpecial: 'Must include special characters',
  mustBeCharaters: 'Must be 8-10 charaters',
  newPassword: 'New Password',
  confirmNewPass: 'Confirm New Password',
  finish: 'Finish',
  whichLimit: 'Which limit would you like to chnage?',
  currentLimit: 'Current Limit',
  whatLimit: 'What would you like to make your new limit?',
  changeReqDescription:
    'Please give us a brief description why you are requesting this change?',
  briefDescription: 'Brief Description',
  changeLimitPermanentTemp:
    'Do you want the change in limit to be permanent or temporary?',
  temporary: 'Temporary',
  permanent: 'Permanent',
  requestLimitNOne:
    'Please provide any supporting documentation to further illustrate the need for this limit change.',
  requestLimitNTwo:
    'Recommended Documentation includes an Invoice, Statement of Work, Check Image of Incoming Funds, etc.',
  documentationOptional: 'Documentation\n(Optional)',
  requestLimitDisclaimer:
    'Disclaimer: All information will be reviewed and Rethink will reach out if additional documentation/details are required',
  submitRequest: 'Submit Request',
  rethinkCard: 'Rethink Card',
  statement: 'Statement',
  setting: 'Settings',
  support: 'Support',
  referBusiness: 'Refer a business, get',
  virtualCard: 'Virtual Card',
  physicalCard: 'Physical Card',
  manageDebitCard: 'Manage Debit Card',
  activateCard: 'Activate your Rethink card',
  activateCardNote:
    "Give us a call and have this info handy when you're ready to activate your card:",
  makeCall: 'Make Call',
  changeCardPin: 'Change your Debit Card PIN',
  changeCardPinNote:
    'Give us a call and we will help you change your debit card PIN.',
  useRethinkCardWorld: 'Use your Rethink card around the world',
  travelNoticeNOne:
    'Create a travel notice at leasr one day before your trip to keep your debit card working smoothly.',
  travelNoticeNTwo:
    'Your card must be used at least once before a travel notice can be placed.',
  createTravelNotice: 'Create Travel Notice',
  travelNotice: 'Travel Notice',
  makeTravelNoticeNote:
    'Add the countries you will be visiting during your trip and tell us how long you will be traveling',
  country: 'Country',
  chooseCountry: 'Choose Country',
  search: 'Search',
  reportMissingCard: 'Report missing card',
  reportMissingCardNote:
    "Give us a call to report your card is missing.\nWe're here for you 24/7",
  inUnitedStates: 'In the United States',
  international: 'Interational',
  orderReplacementCard: 'Order Replacement Card',
  callUS: 'Call US',
};

export const settingsAccountInformation = [
  'Personal Information',
  'Business Information',
  'Users',
  'Bank Letter',
  'Transfer Limits',
];
export const settings = [
  'Change Password',
  'Biometrics Authentication',
  'App Notifications',
];

export const transactionsTypes = [
  {
    title: 'Income',
    types: ['External Deposit', 'Deposit'],
  },
  {
    title: 'Spending',
    types: [
      'POS Withdrawal',
      'Check',
      'External Withdrawal',
      'ATM Withdrawal',
      'Withdrawal',
      'Express Free',
    ],
  },
];

export const dateRange = [
  'All time',
  'Year to date',
  'Quater to Date',
  'Month to date',
  '1 year',
  '30 days',
  '7 days',
  'Custom',
];

export const activity = ['All activity', 'Income', 'Spending'];
4;

export const type = ['Person', 'Business'];

export const personalInformation = [
  'NAME',
  'EMAIL',
  'MOBILE PHONE',
  'HOME ADDRESS',
];

export const businessInformation = [
  'LEGAL BUSINESS NAME',
  'DBA',
  'PHONE',
  'BUSINESS ADDRESS',
  'MAILING ADDRESS',
];

export const manageRethinkCard = [
  'Activate your Rethink Card',
  'Change PIN',
  'Travel Notice',
  'Report lost or stolen',
  'Order or replace your card',
];

export const activateCardPoints = [
  'Debit card number',
  'Last 4 digits of your SSN',
  'Card CVV',
  'New PIN',
];
